# Site settings
title: South By Drinks

description: The homepage for South By Drinks.

url: https://sxdrinks.com
development: false

# A different destination when we build the site for production.
destination: _public

# Build settings
markdown: kramdown

paginate: 4

assets:
  dirname: assets
  sources:
    - js
    - css
    - images
    - bower_components
  js_compressor: 'uglifier'
  css_compressor:
  cache: true

collections:
  protips:
    output: true
    permalink: /protip/:path/

exclude:
  - CONTRIBUTING.md
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - lint.yml
