# Site settings
title: "@OpenBarATX"
env: production

description: "Find out who's still pouring."
url: https://openbaratx.com

# A different destination when we build the site for production.
destination: _public

# Build settings
markdown: kramdown

paginate: 5

permalink: /:year/:title/

assets:
  dirname: assets
  sources:
    - js
    - css
    - img
    - bower_components
  js_compressor: 'uglifier'
  css_compressor:
  cache: true

collections:
  protips:
    output: true
    permalink: /protip/:path/

exclude:
  - CONTRIBUTING.md
  - README.md
  - config.rb
  - package.json
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - lint.yml
  - js
  - css
